<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Jabatan extends Seeder
{
    public function run()
    {
        $jabatan_data = [
            ['nama_jabatan' => 'Administrator'],
            ['nama_jabatan' => 'Sekretaris Jenderal', 'id_unit' => '100000', 'id_kelas' => '17'],
            ['nama_jabatan' => 'Staf Ahli', 'id_unit' => '105000', 'id_kelas' => '16'],
            ['nama_jabatan' => 'Staf Ahli', 'id_unit' => '106000', 'id_kelas' => '16'],
            ['nama_jabatan' => 'Staf Ahli', 'id_unit' => '107000', 'id_kelas' => '16'],
            ['nama_jabatan' => 'Staf Ahli', 'id_unit' => '108000', 'id_kelas' => '16'],
            ['nama_jabatan' => 'Staf Ahli', 'id_unit' => '109000', 'id_kelas' => '16'],
            ['nama_jabatan' => 'Deputi', 'id_unit' => '101000', 'id_kelas' => '17'],
            ['nama_jabatan' => 'Deputi', 'id_unit' => '102000', 'id_kelas' => '17'],
            ['nama_jabatan' => 'Deputi', 'id_unit' => '103000', 'id_kelas' => '17'],
            ['nama_jabatan' => 'Deputi', 'id_unit' => '104000', 'id_kelas' => '17'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '101100', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '101200', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '101300', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '101400', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '102100', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '102200', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '102300', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '103100', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '103200', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '103300', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '104100', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '104200', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '104300', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Pembantu Deputi', 'id_unit' => '104400', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101101', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101102', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101103', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101201', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101202', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101203', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101203', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101203', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101203', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101301', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101302', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101302', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101302', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101302', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101303', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101401', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101401', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101401', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101401', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '101402', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '101402', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '101402', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '101402', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102101', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102102', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102103', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102201', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102202', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102203', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102203', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102203', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102203', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102301', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102302', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102302', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102302', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102302', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '102303', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '102303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '102303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '102303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103101', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103102', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103103', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103201', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103202', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103203', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103203', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103203', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103203', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103301', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103302', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103302', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103302', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103302', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '103303', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '103303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '103303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '103303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104101', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104102', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104103', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104201', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104202', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104203', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104203', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104203', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104203', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104301', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104302', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104302', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104302', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104302', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104303', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104401', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104401', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104401', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104401', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104402', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104402', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104402', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104402', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '104403', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '104403', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '104403', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '104403', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Kepala Biro', 'id_unit' => '110000', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Kepala Biro', 'id_unit' => '111000', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Kepala Biro', 'id_unit' => '112000', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110100', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110101', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Administrasi Pemerintahan', 'id_unit' => '110101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Tata Naskah', 'id_unit' => '110101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Arsiparis Pelaksana', 'id_unit' => '110101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Sekretaris', 'id_unit' => '110101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Persuratan', 'id_unit' => '110101', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Petugas Penggandaan', 'id_unit' => '110101', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110102', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Penyuluh Kearsipan', 'id_unit' => '110102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Arsiparis Pelaksana', 'id_unit' => '110102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Reproduksi Arsip', 'id_unit' => '110102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Restorasi Arsip', 'id_unit' => '110102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Arsip', 'id_unit' => '110102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Persuratan', 'id_unit' => '110102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110103', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Persandian', 'id_unit' => '110103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Petugas Protokol', 'id_unit' => '110103', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pranata Acara', 'id_unit' => '110103', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Operator Sandi dan Telekomunikasi', 'id_unit' => '110103', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Komandan Satpam', 'id_unit' => '110103', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110103', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Satpam', 'id_unit' => '110103', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110104', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110104', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110104', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110104', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110104', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110104', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110104', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110104', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110105', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110105', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110105', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110105', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110105', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110105', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110105', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110105', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110106', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110106', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110106', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110106', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110106', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110106', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110106', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110106', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110107', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110107', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110107', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110107', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110107', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110107', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110107', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110107', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Arsiparis Muda', 'id_unit' => '110108', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Arsiparis Utama', 'id_unit' => '110108', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Arsiparis Madya', 'id_unit' => '110108', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Arsiparis Pertama', 'id_unit' => '110108', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110108', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110108', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110108', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Analis Kepegawaian Madya', 'id_unit' => '110200', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kepegawaian Muda', 'id_unit' => '110201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kepegawaian Utama', 'id_unit' => '110201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kepegawaian Madya', 'id_unit' => '110201', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Kepegawaian Pertama', 'id_unit' => '110201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Sumber Daya Manusia Aparatur', 'id_unit' => '110201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kepegawaian Pelaksana Lanjutan', 'id_unit' => '110201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kepegawaian Pelaksana', 'id_unit' => '110201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Kepegawaian', 'id_unit' => '110201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Arsiparis Pelaksana', 'id_unit' => '110201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Kepegawaian', 'id_unit' => '110201', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Analis Kepegawaian Muda', 'id_unit' => '110202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kepegawaian Utama', 'id_unit' => '110202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kepegawaian Madya', 'id_unit' => '110202', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Kepegawaian Pertama', 'id_unit' => '110202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Dokter Utama', 'id_unit' => '110202', 'id_kelas' => '15'],
            ['nama_jabatan' => 'Dokter Madya', 'id_unit' => '110202', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Dokter Muda', 'id_unit' => '110202', 'id_kelas' => '11'],
            ['nama_jabatan' => 'Dokter Pertama', 'id_unit' => '110202', 'id_kelas' => '9'],
            ['nama_jabatan' => 'Analis Pengembangan SDM Aparatur', 'id_unit' => '110202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kepegawaian Pelaksana Lanjutan', 'id_unit' => '110202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Penegakan Integritas dan Disiplin SDM Aparatur', 'id_unit' => '110202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Perawat Pelaksana', 'id_unit' => '110202', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Analis Kepegawaian Pelaksana', 'id_unit' => '110202', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Arsiparis Pelaksana', 'id_unit' => '110202', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Analis Kepegawaian Muda', 'id_unit' => '110203', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kepegawaian Utama', 'id_unit' => '110203', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kepegawaian Madya', 'id_unit' => '110203', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Kepegawaian Pertama', 'id_unit' => '110203', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Produk Hukum', 'id_unit' => '110203', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penelaah Perjanjian dan Informasi Hukum', 'id_unit' => '110203', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Konsultasi dan Bantuan Hukum', 'id_unit' => '110203', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengolah Informasi Produk Hukum', 'id_unit' => '110203', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Kepala Bagian', 'id_unit' => '110300', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Muda', 'id_unit' => '110301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Utama', 'id_unit' => '110301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Madya', 'id_unit' => '110301', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Pertama', 'id_unit' => '110301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Penelaah Kebijakan Pengadaan Barang/Jasa', 'id_unit' => '110301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusun Rencana Pengadaan Sarana dan Prasarana', 'id_unit' => '110301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Layanan Pengadaan', 'id_unit' => '110301', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Unit Layanan Pengadaan', 'id_unit' => '110301', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Barang dan Jasa', 'id_unit' => '110301', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Keuangan', 'id_unit' => '110301', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Kepala Subbagian', 'id_unit' => '110302', 'id_kelas' => '9'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '110302', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Sekretaris', 'id_unit' => '110302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Arsiparis Pelaksana', 'id_unit' => '110302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '110302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '110302', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110302', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Muda', 'id_unit' => '110303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Utama', 'id_unit' => '110303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Madya', 'id_unit' => '110303', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Pertama', 'id_unit' => '110303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Penyusun Rencana Kebutuhan Rumah Tangga dan Perlengkapan', 'id_unit' => '110303', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Penataan Sarana dan Prasarana', 'id_unit' => '110303', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Sarana dan Prasarana', 'id_unit' => '110303', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Teknisi Sarana dan Prasarana', 'id_unit' => '110303', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pengemudi', 'id_unit' => '110303', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Muda', 'id_unit' => '110304', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Utama', 'id_unit' => '110304', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Madya', 'id_unit' => '110304', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pengelola Pengadaan Barang/Jasa Pertama', 'id_unit' => '110304', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Kebijakan Barang Milik Negara', 'id_unit' => '110304', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Teknisi Elektronik', 'id_unit' => '110304', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Koordinator Pergudangan', 'id_unit' => '110304', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Sarana dan Prasarana', 'id_unit' => '110304', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Perencana Madya', 'id_unit' => '111100', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Perencana Muda', 'id_unit' => '111101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Perencana Utama', 'id_unit' => '111101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Perencana Madya', 'id_unit' => '111101', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Perencana Pertama', 'id_unit' => '111101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Rencana Program dan Kegiatan', 'id_unit' => '111101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Pengembangan Kinerja', 'id_unit' => '111101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Perencanaan Program', 'id_unit' => '111101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Laporan Akuntabilitas Kinerja', 'id_unit' => '111101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengadministrasi Perencanaan dan Program Kerja', 'id_unit' => '111101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Perencana Muda', 'id_unit' => '111102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Perencana Utama', 'id_unit' => '111102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Perencana Madya', 'id_unit' => '111102', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Perencana Pertama', 'id_unit' => '111102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Perencanaan Anggaran', 'id_unit' => '111102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusun Rencana Kegiatan dan Anggaran', 'id_unit' => '111102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kebijakan Penganggaran', 'id_unit' => '111102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Bahan Perencanaan', 'id_unit' => '111102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Perencana Muda', 'id_unit' => '111103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Perencana Utama', 'id_unit' => '111103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Perencana Madya', 'id_unit' => '111103', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Perencana Pertama', 'id_unit' => '111103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Pengevaluasi Program dan Kinerja', 'id_unit' => '111103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Laporan Akuntabilitas Kinerja', 'id_unit' => '111103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Perencanaan, Evaluasi, dan Pelaporan', 'id_unit' => '111103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '111103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '111200', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '111201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '111201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '111201', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '111201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Organisasi dan Tatalaksana', 'id_unit' => '111201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Manajemen Perkantoran', 'id_unit' => '111201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusun Norma, Standar, Prosedur dan Kriteria', 'id_unit' => '111201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengadministrasi Tata Laksana', 'id_unit' => '111201', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Analis Kebijakan Muda', 'id_unit' => '111202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Kebijakan Utama', 'id_unit' => '111202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Kebijakan Madya', 'id_unit' => '111202', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Kebijakan Pertama', 'id_unit' => '111202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Pengembangan Kinerja', 'id_unit' => '111202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kelembagaan', 'id_unit' => '111202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengolah Data Kelembagaan', 'id_unit' => '111202', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Organisasi', 'id_unit' => '111202', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Analis Pengelola Keuangan APBN Madya', 'id_unit' => '111300', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Muda', 'id_unit' => '111301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Pengelola Keuangan APBN Utama', 'id_unit' => '111301', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Pengelola Keuangan APBN Madya', 'id_unit' => '111301', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Pertama', 'id_unit' => '111301', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Pemeriksaan Pelaporan dan Transaksi Keuangan', 'id_unit' => '111301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Sistem Akuntansi Pusat', 'id_unit' => '111301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penata Laporan Keuangan', 'id_unit' => '111301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Akuntansi', 'id_unit' => '111301', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Muda', 'id_unit' => '111302', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Utama', 'id_unit' => '111302', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Madya', 'id_unit' => '111302', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Pertama', 'id_unit' => '111302', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Transaksi Keuangan', 'id_unit' => '111302', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Sistem Infomasi Pelaksanaan Anggaran', 'id_unit' => '111302', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keuangan', 'id_unit' => '111302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Verifikator Keuangan', 'id_unit' => '111302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Database SPM', 'id_unit' => '111302', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Muda', 'id_unit' => '111303', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Utama', 'id_unit' => '111303', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Madya', 'id_unit' => '111303', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Pertama', 'id_unit' => '111303', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Perbendaharaan', 'id_unit' => '111303', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Sistem Informasi Perbendaharaan', 'id_unit' => '111303', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penata Keuangan', 'id_unit' => '111303', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Bendahara', 'id_unit' => '111303', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Keuangan', 'id_unit' => '111303', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pranata Humas Madya', 'id_unit' => '112100', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Pranata Humas Muda', 'id_unit' => '112101', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pranata Humas Utama', 'id_unit' => '112101', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pranata Humas Madya', 'id_unit' => '112101', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pranata Humas Pertama', 'id_unit' => '112101', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Penyusun Risalah', 'id_unit' => '112101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Materi Sidang', 'id_unit' => '112101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusun Naskah Rapat Pimpinan', 'id_unit' => '112101', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Persidangan', 'id_unit' => '112101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Notulis Rapat', 'id_unit' => '112101', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Rapat', 'id_unit' => '112101', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pranata Humas Muda', 'id_unit' => '112102', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pranata Humas Utama', 'id_unit' => '112102', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pranata Humas Madya', 'id_unit' => '112102', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pranata Humas Pertama', 'id_unit' => '112102', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Hubungan Antar Lembaga', 'id_unit' => '112102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Kerjasama', 'id_unit' => '112102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Rancangan Naskah Perjanjian', 'id_unit' => '112102', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Informasi Kerjasama', 'id_unit' => '112102', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Humas Muda', 'id_unit' => '112103', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pranata Humas Utama', 'id_unit' => '112103', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pranata Humas Madya', 'id_unit' => '112103', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pranata Humas Pertama', 'id_unit' => '112103', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Publikasi', 'id_unit' => '112103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Tata Usaha', 'id_unit' => '112103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusun Bahan Publikasi', 'id_unit' => '112103', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Media Center dan Kemitraan Media', 'id_unit' => '112103', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Sekretaris', 'id_unit' => '112103', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministrasi Analis dan Kemitraan Media', 'id_unit' => '112103', 'id_kelas' => '5'],
            ['nama_jabatan' => 'Pustakawan Muda', 'id_unit' => '112104', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pustakawan Utama', 'id_unit' => '112104', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pustakawan Madya', 'id_unit' => '112104', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pustakawan Pertama', 'id_unit' => '112104', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Tenaga Peliputan', 'id_unit' => '112104', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pustakawan Pelaksana Lanjutan', 'id_unit' => '112104', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Penyusunan Dokumen Kesenian dan Perfilman', 'id_unit' => '112104', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pustakawan Pelaksana', 'id_unit' => '112104', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengelola Perpustakaan', 'id_unit' => '112104', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengadministras Risalah', 'id_unit' => '112104', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Petugas Penggandaan', 'id_unit' => '112104', 'id_kelas' => '4'],
            ['nama_jabatan' => 'Pranata Komputer Madya', 'id_unit' => '112200', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Pranata Komputer Muda', 'id_unit' => '112201', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pranata Komputer Utama', 'id_unit' => '112201', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pranata Komputer Madya', 'id_unit' => '112201', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pranata Komputer Pertama', 'id_unit' => '112201', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Sistem Informasi', 'id_unit' => '112201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pranata Komputer Pelaksana Lanjutan', 'id_unit' => '112201', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Keamanan Sistem Informasi', 'id_unit' => '112201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Komputer Pelaksana', 'id_unit' => '112201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pengolah Data', 'id_unit' => '112201', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Komputer Muda', 'id_unit' => '112202', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Pranata Komputer Utama', 'id_unit' => '112202', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Pranata Komputer Madya', 'id_unit' => '112202', 'id_kelas' => '12'],
            ['nama_jabatan' => 'Pranata Komputer Pertama', 'id_unit' => '112202', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Analis Sistem Informasi', 'id_unit' => '112202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pranata Komputer Pelaksana Lanjutan', 'id_unit' => '112202', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengelola Instalasi Teknologi Informasi', 'id_unit' => '112202', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Pranata Komputer Pelaksana', 'id_unit' => '112202', 'id_kelas' => '6'],
            ['nama_jabatan' => 'Auditor Madya', 'id_unit' => '112300', 'id_kelas' => '13'],
            ['nama_jabatan' => 'Auditor Utama', 'id_unit' => '112300', 'id_kelas' => '14'],
            ['nama_jabatan' => 'Auditor Muda', 'id_unit' => '112300', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Auditor Pertama', 'id_unit' => '112300', 'id_kelas' => '8'],
            ['nama_jabatan' => 'Auditor Muda', 'id_unit' => '112301', 'id_kelas' => '10'],
            ['nama_jabatan' => 'Analis Laporan Hasil Pengawasan', 'id_unit' => '112301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Analis Satuan Pengawas Internal', 'id_unit' => '112301', 'id_kelas' => '7'],
            ['nama_jabatan' => 'Pengadministrasi Umum', 'id_unit' => '112301', 'id_kelas' => '6']
        ];

        foreach ($jabatan_data as $data) {
            $this->db->table('jabatan')->insert($data);
        }
    }
}
