<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    public function run()
    {
        $unitkerja_data = [
            ['id_unit' => '100000', 'nama_unit' => 'Sekretariat Jenderal Dewan Ketahanan Nasional'],
            ['id_unit' => '101000', 'nama_unit' => 'Kedeputian Bidang Sistem Nasional', 'parent_id' => '100000'],
            ['id_unit' => '102000', 'nama_unit' => 'Kedeputian Bidang Pengkajian dan Penginderaan', 'parent_id' => '100000'],
            ['id_unit' => '103000', 'nama_unit' => 'Kedeputian Bidang Politik dan Strategi', 'parent_id' => '100000'],
            ['id_unit' => '104000', 'nama_unit' => 'Kedeputian Bidang Pengembangan', 'parent_id' => '100000'],
            ['id_unit' => '105000', 'nama_unit' => 'Sahli Bidang Ekonomi', 'parent_id' => '100000'],
            ['id_unit' => '106000', 'nama_unit' => 'Sahli Bidang Sosial Budaya', 'parent_id' => '100000'],
            ['id_unit' => '107000', 'nama_unit' => 'Sahli Bidang Pertahanan Keamanan', 'parent_id' => '100000'],
            ['id_unit' => '108000', 'nama_unit' => 'Sahli Bidang Hukum', 'parent_id' => '100000'],
            ['id_unit' => '109000', 'nama_unit' => 'Sahli Bidang Ilmu Pengetahuan dan Teknologi ', 'parent_id' => '100000'],
            ['id_unit' => '101100', 'nama_unit' => 'Urusan Lingkungan Pemerintahan Negara', 'parent_id' => '101000'],
            ['id_unit' => '101101', 'nama_unit' => 'Kelompok Kelembagaan', 'parent_id' => '101100'],
            ['id_unit' => '101102', 'nama_unit' => 'Kelompok Ketatalaksanaan dan Sarana Prasarana', 'parent_id' => '101100'],
            ['id_unit' => '101103', 'nama_unit' => 'Kelompok Sumber Daya Manusia', 'parent_id' => '101100'],
            ['id_unit' => '101200', 'nama_unit' => 'Urusan Lingkungan Alam', 'parent_id' => '101000'],
            ['id_unit' => '101201', 'nama_unit' => 'Kelompok Demografi', 'parent_id' => '101200'],
            ['id_unit' => '101202', 'nama_unit' => 'Kelompok Geografi', 'parent_id' => '101200'],
            ['id_unit' => '101203', 'nama_unit' => 'Kelompok Sumber Daya Alam', 'parent_id' => '101200'],
            ['id_unit' => '101300', 'nama_unit' => 'Urusan Lingkungan Sosial', 'parent_id' => '101000'],
            ['id_unit' => '101301', 'nama_unit' => 'Kelompok Politik Keamanan', 'parent_id' => '101300'],
            ['id_unit' => '101302', 'nama_unit' => 'Kelompok Sosial Ekonomi', 'parent_id' => '101300'],
            ['id_unit' => '101303', 'nama_unit' => 'Kelompok Sosial Budaya', 'parent_id' => '101300'],
            ['id_unit' => '101400', 'nama_unit' => 'Urusan Informasi dan Pengolahan Data', 'parent_id' => '101000'],
            ['id_unit' => '101401', 'nama_unit' => 'Kelompok Pengumpulan dan Pengolahan Informasi', 'parent_id' => '101400'],
            ['id_unit' => '101402', 'nama_unit' => 'Kelompok Telematika', 'parent_id' => '101400'],
            ['id_unit' => '102100', 'nama_unit' => 'Urusan Lingkungan Strategis Nasional', 'parent_id' => '102000'],
            ['id_unit' => '102101', 'nama_unit' => 'Kelompok Politik Keamanan Nasional', 'parent_id' => '102100'],
            ['id_unit' => '102102', 'nama_unit' => 'Kelompok Ekonomi Nasional', 'parent_id' => '102100'],
            ['id_unit' => '102103', 'nama_unit' => 'Kelompok Sosial Budaya Nasional', 'parent_id' => '102100'],
            ['id_unit' => '102200', 'nama_unit' => 'Urusan Lingkungan Strategis Regional', 'parent_id' => '102000'],
            ['id_unit' => '102201', 'nama_unit' => 'Kelompok Politik Keamanan Regional', 'parent_id' => '102200'],
            ['id_unit' => '102202', 'nama_unit' => 'Kelompok Ekonomi Regional', 'parent_id' => '102200'],
            ['id_unit' => '102203', 'nama_unit' => 'Kelompok Sosial Budaya Regional', 'parent_id' => '102200'],
            ['id_unit' => '102300', 'nama_unit' => 'Urusan Lingkungan Strategis Internasional', 'parent_id' => '102000'],
            ['id_unit' => '102301', 'nama_unit' => 'Kelompok Politik Keamanan Internasional', 'parent_id' => '102300'],
            ['id_unit' => '102302', 'nama_unit' => 'Kelompok Ekonomi Internasional', 'parent_id' => '102300'],
            ['id_unit' => '102303', 'nama_unit' => 'Kelompok Sosial Budaya Internasional', 'parent_id' => '102300'],
            ['id_unit' => '103100', 'nama_unit' => 'Urusan Politik Nasional', 'parent_id' => '103000'],
            ['id_unit' => '103101', 'nama_unit' => 'Kelompok Pengumpulan dan Pengolahan Data Politik Nasional', 'parent_id' => '103100'],
            ['id_unit' => '103102', 'nama_unit' => 'Kelompok Perumusan Pengkajian Politik Nasional', 'parent_id' => '103100'],
            ['id_unit' => '103103', 'nama_unit' => 'Kelompok Monitoring dan Evaluasi Politik Nasional', 'parent_id' => '103100'],
            ['id_unit' => '103200', 'nama_unit' => 'Urusan Strategi Nasional', 'parent_id' => '103000'],
            ['id_unit' => '103201', 'nama_unit' => 'Kelompok Perencanaan Strategi Pembangunan Nasional Jangka Panjang', 'parent_id' => '103200'],
            ['id_unit' => '103202', 'nama_unit' => 'Kelompok Rencana Pembangunan Nasional Jangka Sedang dan Pendek', 'parent_id' => '103200'],
            ['id_unit' => '103203', 'nama_unit' => 'Kelompok Evaluasi dan Toleransi Risiko Pembangunan Nasional', 'parent_id' => '103200'],
            ['id_unit' => '103300', 'nama_unit' => 'Urusan Perencanaan Kontijensi', 'parent_id' => '103000'],
            ['id_unit' => '103301', 'nama_unit' => 'Kelompok Rencana Kontinjensi Politik dan Keamanan', 'parent_id' => '103300'],
            ['id_unit' => '103302', 'nama_unit' => 'Kelompok Rencana Kontinjensi Ekonomi', 'parent_id' => '103300'],
            ['id_unit' => '103303', 'nama_unit' => 'Kelompok Rencana Kontinjensi Sosial Budaya', 'parent_id' => '103300'],
            ['id_unit' => '104100', 'nama_unit' => 'Urusan Ekonomi', 'parent_id' => '104000'],
            ['id_unit' => '104101', 'nama_unit' => 'Kelompok Pengembangan Keuangan dan Moneter', 'parent_id' => '104100'],
            ['id_unit' => '104102', 'nama_unit' => 'Kelompok Pengembangan Sektor Riil', 'parent_id' => '104100'],
            ['id_unit' => '104103', 'nama_unit' => 'Kelompok Pengembangan Jasa dan Pariwisata', 'parent_id' => '104100'],
            ['id_unit' => '104200', 'nama_unit' => 'Urusan Sosial Budaya', 'parent_id' => '104000'],
            ['id_unit' => '104201', 'nama_unit' => 'Kelompok Pengembangan Pendidikan', 'parent_id' => '104200'],
            ['id_unit' => '104202', 'nama_unit' => 'Kelompok Pengembangan Keagamaan', 'parent_id' => '104200'],
            ['id_unit' => '104203', 'nama_unit' => 'Kelompok Pengembangan Kesejahteraan Sosial', 'parent_id' => '104200'],
            ['id_unit' => '104300', 'nama_unit' => 'Urusan Hukum dan Perundang-Undangan', 'parent_id' => '104000'],
            ['id_unit' => '104301', 'nama_unit' => 'Kelompok Pengembangan Hukum', 'parent_id' => '104300'],
            ['id_unit' => '104302', 'nama_unit' => 'Kelompok Pengembangan Perundang-undangan', 'parent_id' => '104300'],
            ['id_unit' => '104303', 'nama_unit' => 'Kelompok Pengembangan Penegakan Hukum', 'parent_id' => '104300'],
            ['id_unit' => '104400', 'nama_unit' => 'Urusan Pertahanan Keamanan', 'parent_id' => '104000'],
            ['id_unit' => '104401', 'nama_unit' => 'Kelompok Pengembangan Bela Negara', 'parent_id' => '104400'],
            ['id_unit' => '104402', 'nama_unit' => 'Kelompok Pengembangan Militer dan Kepolisian', 'parent_id' => '104400'],
            ['id_unit' => '104403', 'nama_unit' => 'Kelompok Pengembangan Mobilisasi dan Demobilisasi', 'parent_id' => '104400'],
            ['id_unit' => '110000', 'nama_unit' => 'Biro Umum', 'parent_id' => '100000'],
            ['id_unit' => '111000', 'nama_unit' => 'Biro Perencanaan, Organisasi dan Keuangan', 'parent_id' => '100000'],
            ['id_unit' => '112000', 'nama_unit' => 'Biro Persidangan, Sistem Infromasi dan Pengawasan Internal', 'parent_id' => '100000'],
            ['id_unit' => '110100', 'nama_unit' => 'Koordinator Kelompok Tata Usaha dan Protokol ', 'parent_id' => '110000'],
            ['id_unit' => '110101', 'nama_unit' => 'Sub Koordinator Kelompok Persuratan', 'parent_id' => '110100'],
            ['id_unit' => '110102', 'nama_unit' => 'Sub Koordinator Kelompok Kearsipan', 'parent_id' => '110100'],
            ['id_unit' => '110103', 'nama_unit' => 'Sub Koordinator Kelompok Protokol dan Pengamanan', 'parent_id' => '110100'],
            ['id_unit' => '110104', 'nama_unit' => 'Sub Koordinator Kelompok TU Desisnas', 'parent_id' => '110100'],
            ['id_unit' => '110105', 'nama_unit' => 'Sub Koordinator Kelompok TU Dejiandra', 'parent_id' => '110100'],
            ['id_unit' => '110106', 'nama_unit' => 'Sub Koordinator Kelompok TU Depolstra', 'parent_id' => '110100'],
            ['id_unit' => '110107', 'nama_unit' => 'Sub Koordinator Kelompok TU Debang', 'parent_id' => '110100'],
            ['id_unit' => '110108', 'nama_unit' => 'Sub Koordinator Kelompok TU Sahli', 'parent_id' => '110100'],
            ['id_unit' => '110200', 'nama_unit' => 'Koordinator Kelompok Kepegawaian dan Hukum Biro', 'parent_id' => '110000'],
            ['id_unit' => '110201', 'nama_unit' => 'Sub Koordinator Kelompok Mutasi Pegawai dan Administrasi Kepegawaian', 'parent_id' => '110200'],
            ['id_unit' => '110202', 'nama_unit' => 'Sub Koordinator Kelompok Disiplin dan Pengembangan Pegawai', 'parent_id' => '110200'],
            ['id_unit' => '110203', 'nama_unit' => 'Sub Koordinator Kelompok Hukum', 'parent_id' => '110200'],
            ['id_unit' => '110300', 'nama_unit' => 'Kepala Bagian Perlengkapan dan Pengadaan Barang/Jasa', 'parent_id' => '110000'],
            ['id_unit' => '110301', 'nama_unit' => 'Sub Koordinator Kelompok Pengadaan', 'parent_id' => '110300'],
            ['id_unit' => '110302', 'nama_unit' => 'Sub Koordinator Kelompok Protokol dan TU Pimpinan', 'parent_id' => '110300'],
            ['id_unit' => '110303', 'nama_unit' => 'Sub Koordinator Kelompok Rumah Tangga', 'parent_id' => '110300'],
            ['id_unit' => '110304', 'nama_unit' => 'Sub Koordinator Kelompok Barang Milik Negara', 'parent_id' => '110300'],
            ['id_unit' => '111100', 'nama_unit' => 'Koordinator Kelompok Perencanaan', 'parent_id' => '111000'],
            ['id_unit' => '111101', 'nama_unit' => 'Sub Koordinator Kelompok Rencana Program dan Kinerja', 'parent_id' => '111100'],
            ['id_unit' => '111102', 'nama_unit' => 'Sub Koordinator Kelompok Rencana Anggaran', 'parent_id' => '111100'],
            ['id_unit' => '111103', 'nama_unit' => 'Sub Koordinator Kelompok Evaluasi dan Pelaporan', 'parent_id' => '111100'],
            ['id_unit' => '111200', 'nama_unit' => 'Koordinator Kelompok Organisasi dan Tata Laksana', 'parent_id' => '111000'],
            ['id_unit' => '111201', 'nama_unit' => 'Sub Koordinator Kelompok Tata Laksana', 'parent_id' => '111200'],
            ['id_unit' => '111202', 'nama_unit' => 'Sub Koordinator Kelompok Organisasi dan Fasilitasi RB', 'parent_id' => '111200'],
            ['id_unit' => '111300', 'nama_unit' => 'Koordinator Kelompok Keuangan', 'parent_id' => '111000'],
            ['id_unit' => '111301', 'nama_unit' => 'Sub Koordinator Kelompok Akuntansi dan Pelaporan', 'parent_id' => '111300'],
            ['id_unit' => '111302', 'nama_unit' => 'Sub Koordinator Kelompok Verifikasi', 'parent_id' => '111300'],
            ['id_unit' => '111303', 'nama_unit' => 'Sub Koordinator Kelompok Perbendaharaan', 'parent_id' => '111300'],
            ['id_unit' => '112100', 'nama_unit' => 'Koordinator Kelompok Persidangan dan Humas', 'parent_id' => '112000'],
            ['id_unit' => '112101', 'nama_unit' => 'Sub Koordinator Kelompok Pelayanan Persidangan', 'parent_id' => '112100'],
            ['id_unit' => '112102', 'nama_unit' => 'Sub Koordinator Kelompok Hubungan Antar Lembaga', 'parent_id' => '112100'],
            ['id_unit' => '112103', 'nama_unit' => 'Sub Koordinator Kelompok Hubungan Media dan Publikasi ', 'parent_id' => '112100'],
            ['id_unit' => '112104', 'nama_unit' => 'Sub Koordinator Kelompok Produksi, Dokumentasi dan Perpustakaan', 'parent_id' => '112100'],
            ['id_unit' => '112200', 'nama_unit' => 'Koordinator Kelompok Sistem Informasi', 'parent_id' => '112000'],
            ['id_unit' => '112201', 'nama_unit' => 'Sub Koordinator Kelompok Data dan Keamanan Informasi', 'parent_id' => '112200'],
            ['id_unit' => '112202', 'nama_unit' => 'Sub Koordinator Kelompok Teknologi Informasi', 'parent_id' => '112200'],
            ['id_unit' => '112300', 'nama_unit' => 'Koordinator Kelompok Pengawasan Internal', 'parent_id' => '112000'],
            ['id_unit' => '112301', 'nama_unit' => 'Sub Koordinator Kelompok TU Pengawasan Internal', 'parent_id' => '112300']
        ];

        foreach ($unitkerja_data as $data) {
            $this->db->table('unit_kerja')->insert($data);
        }
    }
}
